// <auto-generated />
using BasedClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasedClub.Data.Migrations
{
    [DbContext(typeof(BasedContext))]
    partial class BasedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BasedClub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kaos murah dengan design elegan",
                            ImageName = "based-club-injut1night.jpg",
                            Name = "Based Club in Just 1 Night",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kaos murah dengan design kekinian",
                            ImageName = "Based-Club-Kitten.jpg",
                            Name = "Based Club Kitten",
                            Price = 140000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kaos murah dengan design yang wow",
                            ImageName = "Based-Club-Retro.jpg",
                            Name = "Based Club Retro",
                            Price = 140000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kaos murah dengan design yang mencengangkan",
                            ImageName = "Based-Club-Bintang.jpg",
                            Name = "Based Club Star",
                            Price = 170000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kaos murah dengan design yang out of the box",
                            ImageName = "Based-Club-Girl.jpg",
                            Name = "Based Club Girl",
                            Price = 190000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kaos murah dengan design yang diluar nalar",
                            ImageName = "Based-Club-Sexy.jpg",
                            Name = "Based Club Ear",
                            Price = 200000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
